### ISSUE TITLE
The code under istio-tutorial is not working, giving errors in Pom.xml on import in codium.

### ISSUE THREAD

**Issue by deepakbajaj** [RedHatTraining/DO378-apps#7]
Failure to find io.quarkus:quarkus-maven-plugin:jar:1.3.4.Final-redhat-00007 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Could not find artifact io.quarkus:quarkus-maven-plugin:jar:1.3.4.Final-redhat-00007 in central (https://repo.maven.apache.org/maven2)
Project build error: Non-resolvable import POM: Could not find artifact com.redhat.quarkus:quarkus-universe-bom:pom:1.3.4.Final-redhat-00007 in central (https://repo.maven.apache.org/maven2)
Project build error: 'dependencies.dependency.version' for io.quarkus:quarkus-resteasy:jar is missing.
Project build error: 'dependencies.dependency.version' for io.quarkus:quarkus-rest-client:jar is missing.
Project build error: 'dependencies.dependency.version' for io.quarkus:quarkus-arc:jar is missing.

![image](https://user-images.githubusercontent.com/8168617/129191723-e2844e71-f82f-45b2-98ef-f42bfd5a3491.png)

**Comment by someth2say** [comment]
Hi @deepakbajaj 
It looks like you are trying to use this tutorial without setting up your Maven settings.
Have you executed the `lab-configure` script before starting the exercise?

Anyway, I would recommend dropping this kind of issue in the Learning Community (https://learn.redhat.com/) that is actively monitored by our dev team.

Hope that helps!

**Comment by deepakbajaj** [comment]
Hi

I was trying to set up all lab exercises in my local environment as my
subscription is about to expire, so while setting up getting this error.

Thanks
